### PR TITLE
 Enhance AlCaVal with SSO Reverse Proxy, React-JS Table, and Server-side Pagination

### PR DESCRIPTION
**Pull request by pkalbhor**
Dear team,

I am excited to share major update to the AlCaVal that will hopefully enhance the user experience. The following changes have been made:

**SSO Reverse Proxy Compatibility:** The AlCaVal has been made compatible with the SSO reverse proxy, getting rid of native authentication.
**React-JS Table Implementation:** The Relvals table has been reimplemented using React-JS, providing an interactive and efficient user experience. This is just the beginning, as we plan to gradually expand the implementation to the entire frontend.
**Server-side Pagination:** Server-side pagination has been added to the AlCaVal, improving performance by fetching only visible data.
**Many small changes:** E.g. to be able to pass entire parameters in _hlt_menu_ field for more control over generating custom HLT configuration.
These updates have been tested and I am now merging these changes to the dev branch to test them in a production environment. I am confident that these changes will greatly improve the functionality and usability of the AlCaVal and provide a better overall user experience.

Best regards,
Pritam

### CODE REVIEW

**Comment by pkalbhor** [comment]
@tvami @malbouis @francescobrivio @saumyaphor4252 @teteumac 
I understand that these are a lot of changes, and I am happy to address any concerns or questions you may have. Please feel free to post your comments, questions, and suggestions in this PR. I would be grateful for your feedback as I merge these changes.
Meanwhile keep posting your view here, I will merge this commit to **dev** branch for production testing. You can test this PR changes on https://alcaval-dev.web.cern.ch/relvals

**Comment by tvami** [comment]
@pkalbhor 
> changes on https://alcaval-dev.web.cern.ch/relvals

lead me to 

Screen Shot 2023-01-30 at 10 52 57

**Comment by pkalbhor** [comment]
Hi @tvami I could not launch it in openshift due to some issue related user permission in docker-file. Once I sort it out, I will notify you to check the link again.

**Comment by pkalbhor** [comment]
Hi @tvami , 
Forgot to notify but as you already know, issue has been resolved and changes are implemented. We had issue with docker container being created which was faulty (was with wrong permission for the application workspace). Amended it by using official python image from dockethub and installed node.js on top of that. 

Access it from here: https://alcaval.web.cern.ch/relvals

I guess this concludes the PR. Let me know if you have any questions

**Pull request merged**
