### PR TITLE
Alcaval ticket controller

### PR DESCRIPTION
**Pull request by teteumac**
add ECAL on alcaval ticket

### CODE REVIEW

**Comment by pkalbhor** [comment]
Matheus, I need to bring to your attention a mistake that occurred in your recent pull request on our repository. You included sensitive information, such as secrets, which should not be made public. This is a serious issue. I want to remind you that this is not the first time that this has happened, I think you are pushing same local changes again this time. I had to request support from Github to delete the previous pull request that had the same mistake. To prevent this from happening again, it's highly recommended that you delete your forked repo and make a new one, and also delete any local changes and clone the project again. Please be more careful in the future and double check your code before submitting a pull request. Let me know if you have any questions or concerns.

**Comment by pkalbhor** [comment]
For ref: @tvami , @malbouis , @francescobrivio , @saumyaphor4252 , @teteumac 
I am requesting GitHub support to delete this PR and it's traces.

**Comment by malbouis** [comment]
> Matheus, I need to bring to your attention a mistake that occurred in your recent pull request on our repository. You included sensitive information, such as secrets, which should not be made public. This is a serious issue. I want to remind you that this is not the first time that this has happened, I think you are pushing same local changes again this time. I had to request support from Github to delete the previous pull request that had the same mistake. To prevent this from happening again, it's highly recommended that you delete your forked repo and make a new one, and also delete any local changes and clone the project again. Please be more careful in the future and double check your code before submitting a pull request. Let me know if you have any questions or concerns.

Pritam, thanks for bringing this up!
It is indeed very important not to share sensitive information. I am also reinforcing it with Matheus right now. I think his mistake is that he committed this new PR to the same branch as the previous and this picked up all of the previous commits.

Let's proceed this way: 

- Matheus will delete his fork to this repo and create a new one
- He will then submit a new PR to a *different branch* (I requested him to send us his local branch before submitting the PR)
- in the meantime, please go ahead and request that this PR be deleted by github

**Comment by tvami** [comment]
@pkalbhor I'm wondering, before going to github, we can just force push to `teteumac:alcaval_ticket_controller` and that should erase everything, no?

**Comment by pkalbhor** [comment]
@tvami , that is certainly an option. @teteumac can remove bad commits(using git rebase or revert) and force push to his repo. Would like to see how it goes(If it shows any traces of old commits in PR description).

**Comment by teteumac** [comment]
Hi Pritam. I rebased as requested by Tamas and deleted the commits from my branch that contained the sensible information. Would you please confirm that the commits have been deleted? I will then proceed now on I'm going to make new changes on top of this branch

**Review by pkalbhor — APPROVED** [review]
Looks good. Congratulations Matheus on your first PR on the AlCaVal! Keep up the good work!

**Comment by pkalbhor** [comment]
> Hi Pritam. I rebased as requested by Tamas and deleted the commits from my branch that contained the sensible information. Would you please confirm that the commits have been deleted? I will then proceed now on I'm going to make new changes on top of this branch

Just remember to fetch and sync your repo with the original repository before committing new commits to avoid merge conflicts. Keep up the good work.

**Pull request merged**
